export const INCREASE_NUM = 'category/increaseNum'
export const DECREASE_NUM = 'category/decreaseNum'
export const CLEAR_NUM = 'category/clearNum'
export const INCREASE_NUM_SAGA = 'category/increaseNumSAGA'
export const DECREASE_NUM_SAGA = 'category/decreaseNumSAGA'